# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEditprofile():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_editprofile(self):
    self.driver.get("http://127.0.0.1:3000/")
    self.driver.set_window_size(1454, 866)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit profile").click()
    self.driver.find_element(By.ID, "new_firstname").click()
    self.driver.find_element(By.ID, "new_firstname").send_keys("Malak")
    self.driver.find_element(By.ID, "new_lastname").click()
    self.driver.find_element(By.ID, "new_lastname").send_keys("Elbanna")
    self.driver.find_element(By.CSS_SELECTOR, ".GreenButton:nth-child(6)").click()
    self.driver.find_element(By.LINK_TEXT, "Edit profile").click()
  
