# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPantry():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pantry(self):
    self.driver.get("http://127.0.0.1:3000/")
    self.driver.set_window_size(1454, 866)
    self.driver.find_element(By.LINK_TEXT, "Profile").click()
    self.driver.find_element(By.LINK_TEXT, "Pantry").click()
    self.driver.find_element(By.ID, "ing").click()
    self.driver.find_element(By.ID, "ing").send_keys("meat")
    self.driver.find_element(By.ID, "ing").send_keys("meat")
    self.driver.find_element(By.ID, "ing").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "ing").click()
    self.driver.find_element(By.ID, "ing").send_keys("pasta")
    self.driver.find_element(By.ID, "ing").send_keys("pasta")
    self.driver.find_element(By.ID, "ing").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "ing").click()
    self.driver.find_element(By.ID, "ing").send_keys("jalapeno pepper")
    self.driver.find_element(By.ID, "ing").send_keys("jalapeno pepper")
    self.driver.find_element(By.ID, "ing").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".GreenButton").click()
    self.driver.find_element(By.ID, "Gefilte Fish").click()
    self.driver.find_element(By.LINK_TEXT, "Directions").click()
    self.driver.find_element(By.LINK_TEXT, "Back").click()
    self.driver.find_element(By.ID, "preference").click()
    self.driver.find_element(By.LINK_TEXT, "Vegan").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Recipe-Box:nth-child(7) .GreenButton:nth-child(4)").click()
  
